version: '3'
services:
  app:
    image: mi-aplicacion
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "TuContraseña123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
